name: Funix - SFTP Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout code
        uses: actions/checkout@v4

      - name: 📤 Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          server: ${{ secrets.FTP_HOST }}
          port: 65002
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: './'
          remote_path: 'domains/funixdigital.com/public_html/'
          sftp_only: true
          delete_remote_files: false
          rsyncArgs: '--exclude=.git* --exclude=.github --exclude=node_modules --exclude=vendor --exclude=tests --exclude=storage/logs --exclude=.env --exclude=bootstrap/cache/*.php'