name: Funix - SFTP Deploy Laravel

on:
  push:
    branches:
      - main   # Change if your default branch is different

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout code
        uses: actions/checkout@v3

      - name: 📤 Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_HOST }}
          port: 65002
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: './'
          remote_path: 'domains/funixdigital.com/public_html/'
          sftp_only: true
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/vendor/**          # don’t upload vendor
            **/tests/**
            **/storage/logs/**
            **/.env
            **/bootstrap/cache/*.php
